# Generated by Django 3.1 on 2020-11-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201102_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='maker',
            field=models.CharField(default='', max_length=300),
        ),
    ]
