# Generated by Django 3.1 on 2020-11-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201102_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='licanse',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
