# Generated by Django 3.1 on 2020-11-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201102_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
