# Generated by Django 3.1 on 2020-11-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='licanse',
            field=models.ImageField(default='', upload_to='mysite/licenses/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='', upload_to='mysite/photos/'),
        ),
    ]
