# Generated by Django 3.1 on 2020-11-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201102_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='licanse',
            new_name='license',
        ),
    ]
