# Generated by Django 3.1 on 2020-11-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201102_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
