# Generated by Django 3.1 on 2020-11-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
