# Generated by Django 3.1 on 2020-11-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_service',
            field=models.DateTimeField(verbose_name='Последнее ТО'),
        ),
        migrations.AlterField(
            model_name='car',
            name='maker',
            field=models.CharField(default='', max_length=300, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=300, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Прикрепленный водитель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rented',
            field=models.BooleanField(default=False, verbose_name='Сдается'),
        ),
        migrations.AlterField(
            model_name='car',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(max_length=300, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='license',
            field=models.ImageField(default='', upload_to='mysite/licenses/', verbose_name='Права'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='', upload_to='mysite/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(max_length=300, verbose_name='Тип ТС'),
        ),
    ]
