# Generated by Django 3.1 on 2020-11-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201102_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='Штук в наличии'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='services',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='services',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(verbose_name='Время начала работ'),
        ),
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Комментарий'),
        ),
    ]
