# Generated by Django 3.1 on 2020-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201102_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='stock',
            field=models.IntegerField(default=True, verbose_name='Штук в наличии'),
        ),
    ]
