# Generated by Django 3.1 on 2020-11-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201102_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_service',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее ТО'),
        ),
    ]
