# Generated by Django 3.1 on 2020-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201102_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(default='', upload_to='mysite/cars/', verbose_name='Фото'),
        ),
    ]
