# Generated by Django 3.1 on 2020-11-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_car_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Наименование работ'),
            preserve_default=False,
        ),
    ]
