# Generated by Django 3.1 on 2020-11-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_services_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='car',
            new_name='vehicle',
        ),
    ]
